### PR TITLE
Add ref to Steering Committee past members list from the main SC doc

### PR DESCRIPTION
**Pull request by Andersson007**
Add ref to Steering Committee past members list from the main SC doc

### CODE REVIEW

**Comment by Andersson007** [comment]
@felixfontein if you take a quick look, it would be great

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
An unrelated thought: should we order the SC member list alphabetically? Or at least the 'initial batch', if new members should always be added at the bottom? Right now the order is somewhat arbitrary.

**Comment by gundalow** [comment]
I think sorting alphabetically is OK. I'm not sure if being added earlier should mean someone is higher in the list.

**Comment by Andersson007** [comment]
Great suggestions, thanks! I'll implement both in the next PR:)

**Pull request merged**
