### PR TITLE
maintaining.rst: elaborate on importance of Contributor Summit

### PR DESCRIPTION
**Pull request by Andersson007**
maintaining.rst: elaborate on importance of Contributor Summit

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
ready for review

**Review by gundalow — APPROVED** [review]
These are great updates. Really well written. Thank you.

**Comment by Andersson007** [comment]
@gundalow thanks for reviewing!

**Pull request merged**
