### PR TITLE
SC members: replace with table, make the list alphabetical

### PR DESCRIPTION
**Pull request by Andersson007**
Relates to a discussion in https://github.com/ansible/community-docs/pull/53

- replace the list with table
- use github instead of matrix/irc (not everyone has it, there can be multiple nicknames; in short GitHub login is something more stable
- put names alphabetically

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @felixfontein @gundalow

**Review by gundalow — APPROVED** [review]
Good use of table

**Comment by gundalow** [comment]
Please remove the numbers, I don't think they add anything, and will just require extra work when adding new people (causing every time after to be updated)

**Comment by Andersson007** [comment]
> Please remove the numbers, I don't think they add anything, and will just require extra work when adding new people (causing every time after to be updated)

agreed, done, thanks!

**Review by felixfontein — APPROVED** [review]

**Comment by Andersson007** [comment]
@gundalow @felixfontein thanks for reviewing!

**Pull request merged**
